version: "3"
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
  teamcity-agent1:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent1
  teamcity-agent2:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent2
  teamcity-agent3:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent3
  teamcity-agent4:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent4
  teamcity-agent5:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent5